# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { except_tables = ["feeds_fts", "articles_fts"] }

[migrations_directory]
dir = "./migrations"
